- .travis.yml
- app/adapters/application.js
- app/controllers/items.js
- app/models/issue.js
- app/routes/items.js
- app/serializers/application.js
- app/serializers/issue.js
- app/templates/items.hbs
- bower.json
- config/environment.js
- package.json
- tests/unit/controllers/items-test.js
- tests/unit/serializers/issue-test.js
I created a serializer to handle parsing of githubData attribute but I think, the model should be changed so that the serializer can just set those porperties directory on the model, so instead of 
`issue.githubData.state`
it would be
`issue.state`
If you are cool with that, I can issue another PR
> switched from firebase to pouchdb

- app/styles/app.scss
- package.json
- yarn.lock
This PR is addressing this issue: https://github.com/EndangeredMassa/ember-help-wanted/issues/4
I'm not sure whether to follow a certain style guide or not, so I chose the simplest solution, it should be works well enough.
> Add "active" CSS for the currently selected category

- app/components/issues-table.js
- app/models/github-issue.js
- app/templates/issues.hbs
- package.json
- yarn.lock
This gives us a much more user-readable view of when an issue was last updated:
> moving to use ember-moment again for time-since-now

- README.md
- server/proxies/api-proxy.js
This just prevents any potential contributors to the Frontend of this app needing to actually run the backend locally 👍
> remove the need for a local server for development

- app/models/github-issue.js
@EndangeredMassa I have created PR to solve that issue temporarily. I'll investigate in depth to see if I could able to solve in different way with using hasMany relationship.
https://github.com/ember-learn/ember-help-wanted/issues/85
> HasMany relationship removed in github issue model

- app/styles/app.scss
- app/templates/application.hbs
- package.json
- yarn.lock
This is just a clean rebase of #90 on master 
@EndangeredMassa can you approve this again please before I merge it, I just wanted to keep git history clean 👍 
Fixes #90
> Mobile navigation clean

- app/styles/_loading-cube.scss
- app/styles/app.scss
- app/templates/loading.hbs
- yarn.lock
This PR adds a loading substate when navigating categories.
Animation took from the [ember/website](https://github.com/emberjs/website/blob/3f146ca04d7cf80145d2db0ea5122a437b22869a/source/builds/index.html.erb)
> Add a loading substate

- app/components/github-label.js
- app/controllers/issues.js
- app/helpers/label-with-emoji.js
- app/routes/issues.js
- app/styles/app.scss
- app/templates/components/github-label.hbs
- app/templates/issues.hbs
- mirage/factories/github-issue.js
- tests/acceptance/basic-test.js
- tests/acceptance/filter-test.js
- tests/integration/helpers/label-with-emoji-test.js
This PR adds a feature where the user will be able to click on a label and filter all the issues by that filter.
Example:
> [Feature] / Filter by labels

- README.md
I just stumbled opon this referencing an old, now archieved, repo.
Also Slack 😄
> Update Slack and Backend

- app/styles/app.scss
- app/templates/issues.hbs
- tests/acceptance/basic-test.js
#107 
This PR adds an issues count to know how many issues are currently displayed.
> Add issue count

- app/controllers/application.js
- app/styles/app.scss
- app/templates/application.hbs
> Removes Unnecessary navbar styles and Adds ember styleguide navbar with home button

- app/controllers/index.js
- app/controllers/issues.js
- app/services/nav-links.js
- app/styles/app.scss
- app/templates/application.hbs
- app/templates/index.hbs
- app/templates/issues.hbs
- package.json
- yarn.lock
#121 
- https://github.com/webpack/webpack/issues/8768
> help wanted app should use same navbar as emberjs.com

- app/services/github-issues.js
> Add ember-paper, ember-leaflet, and ember-concurrency to the community list

- app/routes/index.js
- server/proxies/api-proxy.js
@MelSumner 
Addresses #133 
See server companion https://github.com/ember-learn/ember-help-wanted-server/pull/17
> Move repo query to server

- app/templates/index.hbs
- app/templates/issues.hbs
- package.json
- yarn.lock
Updated from 4.0.2 to current version which is 5.0.0
Closes #162
> Update ember styleguide

- .eslintrc.js
- .template-lintrc.js
- app/adapters/application.js
- app/components/github-label.js
- app/controllers/issues.js
- app/models/github-issue.js
- app/models/github-repository.js
- app/routes/issues.js
- app/serializers/github-issue.js
- app/services/github-issues.js
- app/templates/index.hbs
- app/templates/issues.hbs
This PR attempts to close #176 and resolves the following lint errors:
> **eslint-plugin-ember**
> * [no-get](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-get.md)
> * [require-computed-macros](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/require-computed-macros.md)
> * [use-ember-data-rfc-395-imports](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/use-ember-data-rfc-395-imports.md)
> 
> **ember-template-lint**
> * [link-rel-noopener](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/link-rel-noopener.md)
> * [no-action](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-action.md)
> * [no-curly-component-invocation](https://github.com/ember-templ …
> Fix lint errors

- .github/workflows/ci.yml
- README.md
- package.json
- tests/acceptance/index-test.js
- tests/acceptance/issues-test.js
- yarn.lock
This pull request can close https://github.com/ember-learn/ember-help-wanted/issues/187.
I recommend reviewing commits one by one. Each commit makes a small, meaningful change.
- https://crunchingnumbers.live/2020/08/31/ci-with-github-actions-for-ember-apps-part-2/
- https://docs.percy.io/docs/ember
- https://github.com/sinonjs/fake-timers
> Updated CI workflow to run Percy

- README.md
Since I updated the readme last a bunch of work has been done. Updating to reflect that
> Updating the readme to reflect current status

- app/adapters/application.js
- app/controllers/issues.js
- app/services/github-issues.js
It converts some files to use native classes.
#197 
> e.g. screenshot
As the author of this Pull Request I made sure that:
> Refactor native classes

- app/routes/issues.js
Fix for issue https://github.com/ember-learn/ember-help-wanted/issues/196
As part of first commit , I 
1) Finished Step 1 , 2 and 4  
2) Run linting and fix lint issues
3) Run yarn test and confirm all the tests case passed with no regression
TODO: Step 3 adding application acceptance test TBD
> add filter function that makes case insensitive checks for title (#196)

- app/routes/index.js
- app/routes/issues.js
- app/routes/pull-requests.js
- app/templates/application.hbs
See #244 for rationale
Revert once the problem is fixed
> Show maintenance message temporarily - site is down

- config/deprecation-workflow.js
- package-lock.json
- package.json
This is needed for tracking what we need to fix before bumping to Ember v4
> setup deprecation workflow

- app/templates/pull-requests.hbs
there was a local-class in pull-requests.hbs that wasn't pointing at anything 🫠 delete it!
> fix strange hbs file in styles folder
